### ISSUE TITLE
Síntesis

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/actividad-3-sintesis-IMA-G#2]

**Comment by IMA-G** [comment]
[Síntesis Webinar.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-IMA-G/files/9453471/Sintesis.Webinar.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
Calificacion 18
